# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            崔超的博客
tagline:          'Simple is Best.'
description:      '保持简单'
url:              http://cuichaox.github.io
baseurl:          /

author:
  name:           'cuichao'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
