# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            '我是崔超'
tagline:          'Simple is Best.'
description:      '保持简单'
url:              http://cuichaox.github.io
baseurl:          http://cuichaox.github.io

author:
  name:           'cuichao'
  url:            https://cuichaox.github.io

paginate:         5

# Custom vars
version:          1.0

github:
  repo:           https://github.com/cuichaox/cuichaox.github.io
